Cannandev/org selection close action
cloud-gov/cg-ui pull request #518
Opened 2024-09-20 19:42 UTC by cannandev

## Changes proposed in this pull request:

- Close org picker when clicking outside of the list.
- Close org picker when pressing <kbd>Esc</kbd>.
- Close org picker when pressing <kbd>Tab</kbd> _after the last item_ ("View all organizations" link).
  - Focus back on toggle button.

### Related issues

#409 
#464 

### Submitter checklist

- [ ] Added logging is not capturing sensitive data and is set to an appropriate level (DEBUG vs INFO etc)
- [ ] Updated relevant documentation (README, ADRs, explainers, diagrams)

## Security considerations

UI changes only.

## Accessibility considerations

I didn't feel comfortable trapping the tab focus _within_ the picker. [I used this pattern as an example](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation-hybrid/).
 
Tabbing past the last link simply closes the picker and focuses back on the toggle. This allows the user to decide if they want to reopen the menu OR go onto the next focusable element on the page. I'm open to discussing 🗣️

2024-09-23 14:50 UTC, beepdotgov requested changes
This looks and works _great_, @cannandev. Left one suggestion/comment, but that’s all I’ve got. Thanks for thinking so deeply about this interaction 🚀

2024-09-23 15:07 UTC, echappen commented
[blocking request] I second Ethan's comments, it's working beautifully! I noticed that clicking to the right of the open component wouldn't close it. (I'm using Chrome but saw it on FF and Safari as well.) I think this has to do with the `handleOutsideClick` ref containing too big of an area (see screenshot):

![Screenshot 2024-09-23 at 9 43 26 AM_CHROME](https://github.com/user-attachments/assets/b29a14e0-3d32-48eb-86e2-d79b8cc58ce4)

What we could do instead is assign`orgPickerRef` to the `<nav id="orgs-selector"` element (or create another ref entirely so we don't mess with your other keyboard event handlers), which would target this area:

![Screenshot 2024-09-23 at 9 56 34 AM](https://github.com/user-attachments/assets/86baf4ed-3836-4e9d-af8f-2fc0149ffc33)

Code would look something like:
```
const orgPickerRef = useRef<HTMLDivElement>(null);
const orgsSelectorRef = useRef<HTMLElement>(null); // new ref for click events

// ....

// Close the picker when clicking outside
  const handleOutsideClick = (e: MouseEvent) => {
    if (orgsSelectorRef.current && !orgsSelectorRef.current.contains(e.target as Node)) {
      setIsOpen(false);
    }
  }

// .... in the markup ....

<nav
    id="orgs-selector"
    ref={orgsSelectorRef}
>
```

2024-09-23 19:40 UTC, cannandev commented
@echappen 🤦🏾‍♀️ To be fair, there's no reason my other actions can't reference the `<nav>` instead of the parent `<div>`. Updating today.

2024-09-24 01:57 UTC, cannandev commented on src/components/OrgPicker/OrgPicker.tsx
> +      setIsOpen(false);
Yes! Thanks for catching that. I've got it with the latest commits. Ready for re-review. 🔍

2024-09-24 02:00 UTC, cannandev commented
@echappen Ok, I replaced the orgPicker with the orgsSelectorRef. Works as expected. Please re-review. 🔍 
I also combined listeners into 2 separate functions so it's easier to read.

2024-09-24 14:04 UTC, echappen submitted a review, later dismissed
Looks great!

2024-09-24 14:31 UTC, beepdotgov commented on src/components/OrgPicker/OrgPicker.tsx
> +      setIsOpen(false);
Looks and works GREAT, thanks @cannandev!

2024-09-24 14:32 UTC, beepdotgov submitted a review, later dismissed

2024-09-24 15:25 UTC, beepdotgov approved these changes

2024-09-24 15:25 UTC, merged